### ISSUE TITLE
running bars_data_oivae.py gives error

### ISSUE THREAD

**Issue by GlastonburyC** [samuela/oi-vae#1]
Hi, 
I'm trying to test out the oi-VAE using the `bars_data_oivae.py` code.

I get the following error:

```
Traceback (most recent call last):
  File "bars_data_oivae.py", line 267, in <module>
    mc_samples=mc_samples
  File "/Users/craig/oi-vae/lib/oivae.py", line 50, in step
    z_kl = KL_Normals(q_z, self.prior_z.expand_as(q_z)) / batch_size
  File "/Users/craig/oi-vae/lib/distributions.py", line 55, in expand_as
    self.mu.expand_as(*args, **kwargs),
TypeError: expand_as(): argument 'other' (position 1) must be Tensor, not Normal
```

I'm using Python 3.7 and torch 0.4.1

**Comment by samuela** [comment]
This library requires PyTorch version 0.3, so that's likely the cause of the issue. Let me know if that works for you!

At some point I may do a PyTorch 1.0 rewrite, but that's not currently on the roadmap.
